version: "3.8"

services:

  frontend:
    image: programmer175/frontend_arm:latest
    ports:
      - "80:80"
    volumes:
      - frontend:/usr/share/nginx/html
    depends_on:
      - db
      - backend
    
  backend:
    image: programmer175/backend_arm:latest
    ports:
      - "8000:8000"
    volumes:
      - backend:/app
    depends_on:
      - db
    environment:
      POSTGRES_DB: conduit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres


  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: conduit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres

volumes:
  frontend:
  postgres_data:
  backend: