apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit
      type: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: conduit
        type: frontend
    spec:
      containers:
      - name: backend
        image: programmer175/conduit_angular:latest
        ports:
        - containerPort: 80